Remove the explicit dependency libexpat
This is causing:

ERROR: unable to select packages:
  libexpat-2.5.0-r2:

  breaks: world[libexpat=2.6.3-r0]
  satisfies: fontconfig-2.14.2-r4[so:libexpat.so.1]

The dependency was added a while back in:

https://github.com/hypothesis/report/pull/369 as it seemed to be missing

from the docker image but it's not a problem anymore.